/*
  Adds the AI assistant's vector store to the journal database.

  The assistant used to run against a separate database holding its own copy
  of the journal models, populated only by its seed scripts -- so it answered
  questions from data the user had never written. Both apps now share this
  database, and this app owns the schema: the assistant reads these tables and
  never migrates them.

  This consolidates the four DocumentChunk migrations from the assistant's own
  history (add_document_chunks, make_document_chunks_idempotent,
  add_document_chunk_userid, add_embedding_model_version) into the table's
  final shape. Purely additive: nothing here alters or drops an existing table.
*/

-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "vector";

-- CreateTable
CREATE TABLE "DocumentChunk" (
    "id" SERIAL NOT NULL,
    "injuryId" INTEGER NOT NULL,
    -- Denormalized from Injury.userId so chunks can be filtered by user
    -- without joining through Injury on every query.
    "userId" INTEGER NOT NULL,
    "sourceType" TEXT NOT NULL,
    "sourceId" INTEGER NOT NULL,
    "chunkIndex" INTEGER NOT NULL,
    "content" TEXT NOT NULL,
    "embedding" vector(1024),
    -- Which model produced the vector. Cosine distance between vectors from
    -- different models is meaningless, and vector(1024) carries no way to
    -- tell them apart, so retrieval checks these before comparing.
    "embeddingModel" TEXT NOT NULL,
    "embeddingModelVersion" TEXT NOT NULL,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "DocumentChunk_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "DocumentChunk_injuryId_idx" ON "DocumentChunk"("injuryId");

-- CreateIndex
CREATE INDEX "DocumentChunk_userId_idx" ON "DocumentChunk"("userId");

-- CreateIndex
CREATE INDEX "DocumentChunk_sourceType_sourceId_idx" ON "DocumentChunk"("sourceType", "sourceId");

-- CreateIndex
CREATE INDEX "DocumentChunk_embeddingModel_embeddingModelVersion_idx" ON "DocumentChunk"("embeddingModel", "embeddingModelVersion");

-- CreateIndex
-- Makes re-ingesting the same source idempotent.
CREATE UNIQUE INDEX "DocumentChunk_sourceType_sourceId_chunkIndex_key" ON "DocumentChunk"("sourceType", "sourceId", "chunkIndex");

-- AddForeignKey
-- CASCADE, not the assistant's original RESTRICT: a chunk is derived data
-- regenerated by ingestion, not something the user authored, so it should not
-- block deleting an injury. The journal's own FKs are RESTRICT and already
-- make DELETE /api/injuries/:id fail (issue #44); this does not add to that.
ALTER TABLE "DocumentChunk" ADD CONSTRAINT "DocumentChunk_injuryId_fkey" FOREIGN KEY ("injuryId") REFERENCES "Injury"("id") ON DELETE CASCADE ON UPDATE CASCADE;
